project:
  type: website
  output-dir: docs
  
execute: 
  cache: true
  freeze: auto

website:
  title: "FIP606"
 
  navbar:
   pinned: true
   left:
     - text: Importação de dados 
       href: aula2.qmd
     -  text: Estatística descritiva
        menu:
          - href: aula3.qmd
            text: Estatística descritiva- parte 1
          - href: aula4.qmd
            text: Estatistica Descritiva- parte 2
          - href: Exercicio.qmd
            text: Estatistica Descritiva- parte 3 
     -  text: Estatística inferencial
        menu:
          - href: aula6.qmd
            text: ANOVA- parte 1
          - href: Aula8.qmd
            text: ANOVA- parte 2
          - href: aula7.qmd
            text: Estatística não-parametrica
          - href: Aula9.qmd
            text: Análise de Regressão
          - href: Aula10.qmd
            text: Análise de Correlação
     - text: Mapas 
       href: aula11.qmd
     -  text: Projeto Germinação
        menu:
          - href: arquivo1.qmd
            text: Pré-visualização
          - href: arquivo2.qmd
            text: Análise Estatística


  
  
             
             
format:
  html:
    fontsize: 1.1em
    theme: 
      light: sandstone
      dark: darkly
    toc: true
    code-copy: true
    code-overflow: wrap
    warning: false

editor: visual


